name:                persistent-template-classy
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/persistent-template-classy#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  persistent-template-classy:
    source-dirs:      src
    main:             Main.hs
