name:                persistent-template-classy
version:             0.1.0.1
synopsis:            Generate classy lens field accessors for persistent models
description:         Generate classy lens field accessors for persistent models.
homepage:            https://github.com/k-bx/persistent-template-classy#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           2018 Kostiantyn Rybnikov
category:            Database, Lens, Yesod
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - persistent
  - persistent-sqlite
  - persistent-template
  - lens
  - text
  - template-haskell

library:
    source-dirs:      src

tests:
  persistent-template-classy-example:
    main: examples/persistent-template-classy-example.hs
    dependencies:
      - persistent-template-classy
